#! /usr/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source ${SCRIPT_DIR}/setup-paths.sh

mkdir -p ${FUSILLI_PLUGIN_BUILD_DIR}
cmake -G Ninja -B ${FUSILLI_PLUGIN_BUILD_DIR} \
    -S ${FUSILLI_DIR} \
	-DCMAKE_BUILD_TYPE=Release \
	-DFUSILLI_BUILD_TESTS=OFF \
	-DFUSILLI_BUILD_BENCHMARKS=OFF \
	-DFUSILLI_SYSTEMS_AMDGPU=ON \
	-DFUSILLI_CODE_COVERAGE=OFF \
	-DFUSILLI_ENABLE_LOGGING=OFF \
	-DFUSILLI_ENABLE_CLANG_TIDY=OFF \
	-DIREE_SOURCE_DIR=$IREE_DIR \
	-DHIP_DIR=${HIP_DIR}/lib/cmake \
	-DHIP_PLATFORM=amd \
	-DIREE_USE_SYSTEM_DEPS=ON

cmake --build ${FUSILLI_PLUGIN_BUILD_DIR}/
